config/routes.rb
Api::Application.routes.draw do


  #match '*all' => 'application#cor', :constraints => {:method => 'OPTIONS'}

 
  match '/users/edit_avatar', to: 'sessions#isAuth', via: [:options]
  match '/users/edit_avatar', to: 'users#update_avatar', via: [:post, :put]


  match '/users/register_push', to: 'sessions#isAuth', via: [:options]
  match '/users/register_push', to: 'users#update_push_register_id', via: [:post, :put]


  match '/send_push', to: 'application#send_push', via: [:get]


  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
  
  devise_scope :user do
    match '/users', to: 'registrations#new', via: [:options]
    match '/users/:id', to: 'sessions#isAuth', via: [:options]

    match '/users/:id', to: 'users#show', via: [:get]


    match '/users/:user_id/conversations', to: 'sessions#isAuth', via: [:options]
    match '/users/:user_id/conversations/:id', to: 'sessions#isAuth', via: [:options]
    match '/users/:user_id/conversations/:id/messages', to: 'sessions#isAuth', via: [:options]
    match '/users/:user_id/conversations/:id/send_message', to: 'sessions#isAuth', via: [:options]
    match '/users/:user_id/conversations/:id/send_message', to: 'conversations#send_message', via: [:post]



    match '/users/sign_in', to: 'sessions#create', via: [:options]
    match '/users/sign_out', to: 'sessions#destroy', via: [:options]
    match '/users/:id/contacts.json', to: 'sessions#isAuth', via: [:options]
    match '/users/:user_id/contacts/:id', to: 'sessions#isAuth', via: [:options]
  end


  resources :users do
    resources :contacts
    resources :conversations do
      resources :messages
    end
  end





  root to: "main#index"
 
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  # 
   
   
  
  def index
    @contacts = Contact.where(:user_id => current_user.id)
    respond_to do |format|
      format.json { render json: @contacts.to_json }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    render json: @contact.to_json
  end


  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
      render json: @contact.to_json, status: :created
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    if @contact.update(contact_params)
      head :no_content
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    render :json => {
      :success => true
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :avatar, :user_token, :user_email)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact),  :html => { :multipart => true } do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.user %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @contact.user %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>